### ISSUE TITLE
很不错的批处理tiny压缩工具有几点问题

### ISSUE THREAD

**Issue by kvkens** [xueqing325/TinyPNGNodeJSBatcher#1]
1. 没有`package.json`文件，导致我使用的时候提示找不到`tinify`，我又自己安装在本地的`npm install tinify` 应该是你有全局的原因吧。
2. 尽量不要提交`node_modules`文件夹这个在`package.json`配置上就好我看到用了一个`express`.
3. 继续努力，尽量把它做成cli这样的工具，可以安装全局使用，不需要去指定运行某文件，还可以做成类似`nova`这样的本地配置文件来配置API KEY，有时间我也可以来完善 :)

**Comment by qjoy** [comment]
多谢，源于本人对nodejs还不是很了解。最近恶补一下，完善工程。很感谢提出的宝贵意见。

**Comment by kvkens** [comment]
我忙完最近的项目我fork下来进行改造吧，说实话非常需要这个工具，我会按照我的想法试试，嘿嘿。
好的话我会放在我们团队的官网上的，继续开源，你不会介意吧，会保留署名的。

**Comment by qjoy** [comment]
当然，希望能够得到完善和发展。这不也是开元精神的体现嘛。祝好。
